name: Lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
            npm install
            composer install
      - name: Run prettier
        if: ${{ always() }}
        run: npm run prettier
      - name: Run stylelint
        continue-on-error: true
        if: ${{ always() }}
        run: npm run stylelint
      - name: Run PHP CS fixer
        continue-on-error: true
        if: ${{ always() }}
        run: composer run cs:check
